### ISSUE TITLE
IEmailService is implementation specific for sending notifications.  

### ISSUE THREAD

**Issue by drewburlingame** [apryiomka/test#1]
How would you modify this to be less specific?  For example, what if in some cases we also wanted to call a WebHook or submit a message to a service bus?

**Comment by apryiomka** [comment]
@drewburlingame, for simplicity sake, i "dumped" everything in one place. ideally, i would have a service bus with stand alone email service. I will dispatch a message, lets call it NotificationMessage, to the service bus and the subscribers to that message will do what ever is needed when they receive it. For example, we can have a stand alone email server whose only propose to "consume" NotificationMessages and send emails. It, probably, wouldn't even care about specific of the email whether it is a notification email or a new user password reset email, just receive the message and send it to the destination. We can have another subscriber, say, SMS service which, when the NotificationMessage is recieved, will send an SMS message, same can be done for mobile apps notifications, etc. With service bus architecture you can have unlimited number of subscribers to the message where each subscriber can handle the message properly (Send email, send SMS, save it to the DB, etc).

**Comment by apryiomka** [comment]
@drewburlingame , i did update the code. What was added: i  added a simile in memory Service Bus, this is just to demonstrate the decoupling and message routing. In the real app the service bus would use some kind of messaging transport like RabbitMQ or Azure Service Bus or something else. We have two subscribers for notification messages: Email and Sms as well as a subscriber to the scheduled message. I also changed the workflow for the error handling and introduced exceptions rather than error code (I like this approach more). I changed the verbs to be POST for the item create and DELETE for the item take. I added validation for the inventory item to validate the dates. I also added "global" exception filters to handle exceptions and response "globally" rather than locally for each action. Some other minor changes. The app is much more polished now, but still "work" in progress, so please let me know if you have questions or want to see more interesting ideas or implementation.
