### ISSUE TITLE
Quartz scalibility

### ISSUE THREAD

**Issue by drewburlingame** [apryiomka/test#2]
Using Quartz is an interesting idea.  How would you scale that for millions of items?

**Comment by apryiomka** [comment]
@drewburlingame, I just answered this question in other comment. I didn't try quartz with millions of records, but it seems like, as per document, [it should be able to handle that.](https://groups.google.com/forum/#!forum/quartz-scheduler). Quartz also allow to scale horizontally with load balancing. You can add more servers to process jobs concurrently.

**Comment by drewburlingame** [comment]
the link appears to just be for the forum, not for a specific thread.  did you have a specific thread in mind?

**Comment by apryiomka** [comment]
@drewburlingame, i don't have any specific number, neither i have tried so many jobs. If the jobs are stored in the DB, i don't think it would be a problem. The quartz performance is mostly about how many concurrent jobs can it run. If we are talking about millions of concurrent jobs, it would be a problem for any system. if we are talking about scheduling a million jobs, meaning they would be distributed over some perioud of time, it might not be a problem. Here is the [link](http://www.quartz-scheduler.org/documentation/faq#FAQ-scale) to how to scale quartz. the link says

> The actual number of jobs that can be running at any moment in time is limited by the size of the thread pool. If there are five threads in the pool, no more than five jobs can run at a time.
**Aside from those factors, it really comes down to what your jobs DO. **
So here you are this far into the answer of "how many", and I still haven't given you an actual number. And I really hate to, because of all of the variables mentioned above. So let me just say, there are installments of Quartz out there that are managing hundreds-of-thousands of Jobs and Triggers, and that are, at any given moment in time executing several dozens of jobs – without even utilizing Quartz's load-balancing capabilities. With this in mind, most people should feel confident that they can get the performance out of Quartz that they need.

It is hard to say because it depends. Depends on the server, number of processors, depends on how heave the jobs are in terms of what they do. Quartz is also was used as an example. There are also more lightweight alternatives, for example [Hangfire
](https://github.com/HangfireIO/Hangfire). If all you need is to delay the execution of a task, it would make sense to use more lightweight library or service.

> Hangfire is a .NET Framework alternative to [resque](https://github.com/resque/resque), [Sidekiq](http://sidekiq.org/), [delayed_job](https://github.com/collectiveidea/delayed_job), etc

**Comment by apryiomka** [comment]
@drewburlingame , i did update the code. What was added: i added a simile in memory Service Bus, this is just to demonstrate the decoupling and message routing. In the real app the service bus would use some kind of messaging transport like RabbitMQ or Azure Service Bus or something else. We have two subscribers for notification messages: Email and Sms as well as a subscriber to the scheduled message. I also changed the workflow for the error handling and introduced exceptions rather than error code (I like this approach more). I changed the verbs to be POST for the item create and DELETE for the item take. I added validation for the inventory item to validate the dates. I also added "global" exception filters to handle exceptions and response "globally" rather than locally for each action. Some other minor changes. The app is much more polished now, but still "work" in progress, so please let me know if you have questions or want to see more interesting ideas or implementation.
