### ISSUE TITLE
Quartz tight coupling

### ISSUE THREAD

**Issue by drewburlingame** [apryiomka/test#3]
IQuartzService is very implementation specific, and InventoryManager is now tightly coupled to a service where it must "ScheduleItemDeletion".  How can InventoryManger be decoupled from Quartz such that Quartz could be an optional choice for tracking item expiration, and if chose a different solution that didn't require scheduling an item, we wouldn't have to change InventoryManager. (Open/Closed Principal)

**Comment by apryiomka** [comment]
@drewburlingame, my apologies for the incomplete code. There are still some rough edges left, For example  IInventoryManager.AddNewItem was supposed to check for the Expiration date not being null and only then schedule a job and also i wanted to have another rule to validate the expiration date to be in future. Now it is only limited to the Label validation. 
To the point, yes, i do agree, the IQuartzService kind of coupled to the manager. Ideally, Quartz, or should you choose to implement any different scheduling mechanism, should be a stand alone service. Ideally, I would use Service Bus architecture to implement this. Lots of things were simplified for the assessment scope, but in the real live system I would have a message queue transport (RabbitMQ or Azure Service Bus) with, say, [Masstransit Service Bus ](http://www.nuget.org/packages/MassTransit/) that will send a message when new item with expiration date (again, only send a message if the item has the expiration date) is added. The "subscriber" to that message, which would be either a quartz or some kind of other service, will receive the message and schedule a job to remove the item from the DB. As an alternative to Service Bus architecture, another web service would be used and expose a web API to "schedule" a message. In this case, whether we use service bus with message queue or another service with web API, the service will be decoupled and can be "swapped" for something else. As far as scalability, quartz can be used with a DB for the back-end, the example i gave, again, for simplicity, is all in memory. Here is the link from the [Document](http://www.quartz-scheduler.org/documentation/faq#FAQ-scale) 

> So let me just say, there are installments of Quartz out there that are managing hundreds-of-thousands of Jobs and Triggers, and that at any given moment in time are executing dozens of jobs – and this excludes using load-balancing.

Quartz allows load balancing to scale horizontally. 
Here is [another topic](https://groups.google.com/forum/#!forum/quartz-scheduler) discussion that suggest quartz can easily handle a couple of million jobs a day or up to 10 jobs per second.

**Comment by drewburlingame** [comment]
no worries about the rough edges.  it was my understanding that you were just asking for feedback on your progress so far, which i appreciate.

with a cluster, Quartz can scale out to hundreds-of-thousands (this forum link isn't to a thread).  this is still an order of magnitude short of millions.  how many machines would that take?  what would be the cost of administering that?  is this a pragmatic choice?  are there alternatives for solving this requirement that are less complex and more performant than 10/sec?

**Comment by apryiomka** [comment]
@drewburlingame, i just replied to your question in [this thread](https://github.com/apryiomka/InventorySystem/issues/2). All i can say is, i do not know how good quartz is for scheduling millions of jobs, i guess we should really test it,, but there are other more lightweight solutions to do that.

**Comment by apryiomka** [comment]
@drewburlingame , i did update the code. What was added: i added a simile in memory Service Bus, this is just to demonstrate the decoupling and message routing. In the real app the service bus would use some kind of messaging transport like RabbitMQ or Azure Service Bus or something else. We have two subscribers for notification messages: Email and Sms as well as a subscriber to the scheduled message. I also changed the workflow for the error handling and introduced exceptions rather than error code (I like this approach more). I changed the verbs to be POST for the item create and DELETE for the item take. I added validation for the inventory item to validate the dates. I also added "global" exception filters to handle exceptions and response "globally" rather than locally for each action. Some other minor changes. The app is much more polished now, but still "work" in progress, so please let me know if you have questions or want to see more interesting ideas or implementation.
