### ISSUE TITLE
ActionResult pattern

### ISSUE THREAD

**Issue by drewburlingame** [apryiomka/test#4]
Can you tell me more about your choice to return ActionResults instead of returning the inventory items and throwing exceptions?  What are the pros & cons of this choice?

**Comment by apryiomka** [comment]
@drewburlingame, the pros of using "messaging" pattern is that you have a standardized object and model that can be used more easily, meaning you can have some common types or service that can handle, say, error response. For example, if your ActionResults  returns an error, you can call a method in a base controller (say you have a base api controller class) class what would check for it and return, say, BadRequest for the error. The disadvantage, of course, is that we might "eat" the exception and might not handle some cases properly. But again, it would depend on the exception handling how it is done. We can still return "errors" for specific cases only, say, validation error, but throw / re-throw exceptions for other, more critical cases. Ideally, if the exception occurs, unless it is a specific expected exception, it should bubble up to the very top of the stack trace.

**Comment by drewburlingame** [comment]
there are numerous posts out there comparing the two, and there are times when one should be used vs the other.  i'm hoping to understand the specific reasons why you chose the return value pattern vs the pattern of throwing exceptions which is the standard in the .net ecosystem.  what makes it more easy for you?  from my experience, all of the examples you gave can just as easily be handled by throwing exceptions and some of the code would be simpler.  for example, i could use several patterns to intercept exceptions and convert them to api responses without tightly coupling the controllers to those exception types, ie Validation, Security, etc.

here are some of the posts i found with reasonable pros & cons.
http://stackoverflow.com/questions/99683/which-and-why-do-you-prefer-exceptions-or-return-codes
http://codeutopia.net/blog/2010/03/11/should-a-failed-function-return-a-value-or-throw-an-exception/
http://yosefk.com/blog/error-codes-vs-exceptions-critical-code-vs-typical-code.html

**Comment by apryiomka** [comment]
Yes, i do agree that we can just throw the exceptions and handle different types. I don't have preference one over another one, honestly, it thing it depends. I will say for sure two things, one is that the exception should always be re-thrown up to the stack if it ever occurs whether it is your custom exception or the framework exception. Whether to use the error codes/ i guess it comes to the design requirements and how the application should behave. i do agree, though, you can always handle specific types of exceptions with proper catch statements. I could also do a better job implementing it, i did cut some corners while implementing the service. As you might have noticed i don't have any internal try catch blocks meaning any IO or security exception will crash the app, or, at least will bubble up. I only did the "error codes" for the validation purposes when, say, the object you sent is not valid. But that can also be done using exceptions. I thinks, the implementation can be exceptions only (throw validation exceptions if the objects are not valid) or mix of both, exceptions and specific error codes, but ** IT SHOULD NEVER BE ** error codes only!!! And, the rule of thumb is to never catch the base exception type.

**Comment by apryiomka** [comment]
@drewburlingame, i will update the code tonight to address some of the issues and refine it a bit.

**Comment by apryiomka** [comment]
@drewburlingame , i did update the code. What was added: i added a simile in memory Service Bus, this is just to demonstrate the decoupling and message routing. In the real app the service bus would use some kind of messaging transport like RabbitMQ or Azure Service Bus or something else. We have two subscribers for notification messages: Email and Sms as well as a subscriber to the scheduled message. I also changed the workflow for the error handling and introduced exceptions rather than error code (I like this approach more). I changed the verbs to be POST for the item create and DELETE for the item take. I added validation for the inventory item to validate the dates. I also added "global" exception filters to handle exceptions and response "globally" rather than locally for each action. Some other minor changes. The app is much more polished now, but still "work" in progress, so please let me know if you have questions or want to see more interesting ideas or implementation.
