### ISSUE TITLE
Take vs Delete

### ISSUE THREAD

**Issue by drewburlingame** [apryiomka/test#5]
Can you tell me about your choice to use DeleteItem vs TakeItem?  Maybe pros & cons of each?

Also, can you tell me about your choice to use Post vs Delete verb for DeleteItem?

**Comment by apryiomka** [comment]
I guess, when you Delete the item, you just delete it without returning the item (true / false pretty much to define success), if I understand correctly, and take item would be like "dequeue" item which will return the item and remove it from the storage. I guess, it depends on the case. If, say, you want the "take" to be a part of  distributed transaction, you might want to "remove" the item only after your transaction succeeds, say, you create a new order, you "take" your item from the cart, the order is now saved successfully, now you can "complete the removal" the item from the cart. If the order failed, say CC card billing or something, you can "unwind" your take transaction and your item is still in the cart.

From the API prospective, using DELETE verb would be more accurate to delete item, because POST is rather used for creates (PUT for updates). I guess from the error handling prospective, is say, you want to DELETE the item that doesn't, we can return 404 error which would be more accurate than say returning 404 to the POST, where as POST should rather create the item if doesn't exist (or update if it does). I did "cut some corners" and just used POST, but i do agree, i should've used DELETE for deletion and post for creation only.

**Comment by apryiomka** [comment]
@drewburlingame , i did update the code. What was added: i added a simile in memory Service Bus, this is just to demonstrate the decoupling and message routing. In the real app the service bus would use some kind of messaging transport like RabbitMQ or Azure Service Bus or something else. We have two subscribers for notification messages: Email and Sms as well as a subscriber to the scheduled message. I also changed the workflow for the error handling and introduced exceptions rather than error code (I like this approach more). I changed the verbs to be POST for the item create and DELETE for the item take. I added validation for the inventory item to validate the dates. I also added "global" exception filters to handle exceptions and response "globally" rather than locally for each action. Some other minor changes. The app is much more polished now, but still "work" in progress, so please let me know if you have questions or want to see more interesting ideas or implementation.
